/** French UI copy � Unicode escapes avoid encoding issues on deploy. */
export const L = {
    myAccount: 'Mon compte',
    myAccountDesc: 'Vos informations personnelles et identifiants de connexion.',
    keysSsh: 'Cl\u00E9s SSH',
    keysSshDesc: 'G\u00E9rez vos cl\u00E9s SSH pour acc\u00E9der \u00E0 vos serveurs.',
    apiTokens: 'Jetons API',
    apiTokensDesc: 'Cr\u00E9ez et g\u00E9rez vos jetons pour l\u2019API client.',
    security: 'S\u00E9curit\u00E9',
    securityDesc: 'Prot\u00E9gez votre compte avec l\u2019authentification \u00E0 deux facteurs.',
    addSshKey: 'Nouvelle cl\u00E9',
    addSshKeyDesc: 'Donnez un nom et collez votre cl\u00E9 publique SSH.',
    savedSshKeys: 'Cl\u00E9s enregistr\u00E9es',
    noSshKeys: 'Aucune cl\u00E9 SSH enregistr\u00E9e.',
    createApiKeyDesc: 'D\u00E9crivez le jeton et d\u00E9finissez les IP autoris\u00E9es si besoin.',
    noApiKeys: 'Aucun jeton API pour le moment.',
    activityDesc: 'Historique des actions r\u00E9centes sur votre compte.',
    noActivity: 'Aucune activit\u00E9 r\u00E9cente pour ce compte.',
    resetFilters: 'R\u00E9initialiser les filtres',
    cloudProjects: 'Mes projets',
    cloudProjectsDesc: 'Projets cloud et plafonds li\u00E9s \u00E0 votre palier mensuel.',
    cloudBilling: 'Facturation cloud',
    cloudBillingDesc: 'Consommation horaire et pr\u00E9l\u00E8vements sur votre compte pr\u00E9pay\u00E9.',
    cloudPlans: 'Paliers cloud',
    cloudPlansDesc: 'Choisissez ou changez votre palier mensuel (RAM et instances).',
    cloudDeploy: 'D\u00E9ployer une instance',
    cloudDeployDesc: 'VM Linux et Windows en priorit\u00E9, jeux et applications disponibles.',
    networkIps: 'Adresse IP',
    networkIpsDesc: 'IPs dédiées LumenVM, routage et reverse DNS.',
    networkDdos: 'Attaque DDoS',
    networkDdosDesc: 'Incidents et modes de filtre anti-DDoS.',
    deployInstance: 'D\u00E9ployer une instance',
    deployInstanceHint: 'Lancez un nouveau serveur cloud en quelques clics.',
    deployNow: 'D\u00E9ployer maintenant',
    prepaidAccount: 'Compte pr\u00E9pay\u00E9',
    connectedAs: 'Connect\u00E9 en tant que',
    logout: 'D\u00E9connexion',
    firstName: 'Pr\u00E9nom',
    username: "Nom d'utilisateur",
    updateEmail: "Mettre \u00E0 jour l'e-mail",
    twoFactorOn: '2FA activ\u00E9e',
    twoFactorOff: '2FA d\u00E9sactiv\u00E9e',
    twoFactorTitle: 'Authentification \u00E0 deux facteurs',
    twoFactorHint: 'Ajoutez une couche de s\u00E9curit\u00E9 suppl\u00E9mentaire \u00E0 votre compte.',
    twoFactorEnabledDesc: 'Votre compte est prot\u00E9g\u00E9 par une application d\u2019authentification.',
    twoFactorDisabledDesc: 'Renforcez la s\u00E9curit\u00E9 de votre compte en activant la 2FA.',
    enableTwoFactor: 'Activer la v\u00E9rification',
    disableTwoFactor: 'D\u00E9sactiver la v\u00E9rification',
    createApiKey: 'Cr\u00E9er un jeton',
    apiKeys: 'Jetons actifs',
    deleteApiKey: 'Supprimer le jeton',
    activityLog: "Journal d'activit\u00E9",
    neverUsed: 'Jamais utilis\u00E9e',
    profileInfo: 'Informations du profil',
    updateEmailSection: 'Adresse e-mail',
    passwordSection: 'Mot de passe',
    credentialsSection: 'Identifiants',
    noProducts: 'Aucun produit trouv\u00E9',
    unlimited: 'Illimit\u00E9',
    allServices: 'Tous les services',
    newProject: 'Nouveau projet',
    editProject: 'Modifier le projet',
    editProjectBtn: 'Editer',
    deleteProject: 'Supprimer le projet',
    deleteProjectConfirm: '\u00CAtes-vous s\u00FBr de vouloir supprimer ce projet ? Cette action est irr\u00E9versible.',
    deleteProjectHint: 'Vos services ne seront pas supprim\u00E9s \u2014 ils deviendront simplement non assign\u00E9s.',
    newProjectHint: 'Regroupez vos services pour rester organis\u00E9.',
    editProjectHint: 'Renommez ou changez la couleur de votre projet.',
    projectName: 'Nom du projet',
    projectNamePlaceholder: 'ex. Production, Staging, Client ABC',
    projectColor: 'Couleur',
    projectPreview: 'Aper\u00E7u du nom du projet',
    projectServices: 'Services assign\u00E9s',
    projectServicesHint: 'S\u00E9lectionnez les services \u00E0 inclure dans ce projet.',
    projectServicesSearch: 'Rechercher un service...',
    projectServicesCount: 'services',
    createProject: 'Cr\u00E9er le projet',
    saveProject: 'Enregistrer',
    dragToProject: 'Glissez un service sur un projet',
    dragToReorder: 'Glissez pour r\u00E9organiser',
    dropOnAllServices: 'D\u00E9poser ici pour retirer du projet',
    billingAutoRenew: 'Paiement automatique',
    billingAutoRenewDesc: 'G\u00E9rez le renouvellement automatique de vos services.',
    billingPrepaid: 'Compte pr\u00E9pay\u00E9',
    billingPrepaidDesc: 'Consultez et rechargez votre solde pr\u00E9pay\u00E9.',
    billingInvoices: 'Factures',
    billingInvoicesDesc: 'T\u00E9l\u00E9chargez et consultez vos factures.',
    billingTransactions: 'Historique des transactions',
    billingTransactionsDesc: 'Consultez l\'historique de tous vos paiements.',
    billingPaymentMethods: 'Moyens de paiement',
    billingPaymentMethodsDesc: 'G\u00E9rez vos cartes, PayPal et compte pr\u00E9pay\u00E9.',
    dashboard: 'Tableau de bord',
    dashboardDesc: 'Vue d\u2019ensemble de vos services et statistiques.',
    support: 'Support',
    supportDesc: 'Ouvrez un ticket ou consultez la FAQ.',
    supportAdmin: 'Gestion support',
    supportAdminDesc: 'Répondez aux tickets et gérez les demandes clients.',
    cloudLimitsAdmin: 'Limites cloud',
    cloudLimitsAdminDesc: 'Acceptez ou refusez les demandes d\u2019augmentation de limites cloud.',
    subUsers: 'Sous utilisateurs',
    subUsersDesc: 'G\u00E9rez les sous-utilisateurs et le partage d\u2019acc\u00E8s \u00E0 vos produits.',
    affiliation: 'Affiliation',
    affiliationDesc: 'Partagez votre lien, suivez les visites et demandez le versement de vos gains.',
    subUsersPageDesc: 'D\u00E9l\u00E9guez la gestion de vos produits \u00E0 des membres de votre \u00E9quipe ou partagez l\u2019acc\u00E8s avec un contact technique.',
    subUsersSectionDesc: 'G\u00E9rez des utilisateurs suppl\u00E9mentaires rattach\u00E9s \u00E0 votre compte, avec des droits de lecture ou d\u2019administration sur des produits d\u00E9finis.',
    shareAccessSectionDesc: 'Partagez l\u2019acc\u00E8s \u00E0 vos produits avec un compte existant. L\u2019utilisateur doit d\u00E9j\u00E0 poss\u00E9der un compte sur la plateforme.',
};
