log syslog all;
router id 77.90.4.48;

protocol device {}

protocol direct {
  ipv4;
  interface "lo";
}

protocol static static_announce {
  ipv4;
  route 79.172.242.0/24 blackhole;
}

filter export_to_pd {
  if net = 79.172.242.0/24 then accept;
  reject;
}

filter import_from_pd {
  if net = 0.0.0.0/0 then accept;
  reject;
}

protocol bgp pd_r1 {
  local 77.90.4.48 as 219084;
  neighbor 77.90.4.247 as 214243;
  ipv4 {
    import filter import_from_pd;
    export filter export_to_pd;
  };
}

protocol bgp pd_r2 {
  local 77.90.4.48 as 219084;
  neighbor 77.90.4.246 as 214243;
  ipv4 {
    import filter import_from_pd;
    export filter export_to_pd;
  };
}
