log syslog all;

# Local Bird on Digi router — transit BGP is on PD VPS (AS219084).
router id 79.172.242.1;

protocol device {
}

protocol static static_announce {
  ipv4;
  route 79.172.242.0/24 blackhole;
}
